spring.application.name=proye01
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/BD-Bomb-v4
spring.datasource.url=jdbc:postgresql://localhost:5432/BD10BOMB
spring.datasource.username=postgres
spring.datasource.password=5432
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

implementation 'org.springframework.boot:spring-boot-starter-cache'
implementation 'com.github.ben-manes.caffeine:caffeine'

sig.mosaicos.sentinelhub.instance-id=1c032970-3cba-42f2-8575-6aedde488f39

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret.key=sandoval
jwt.time.expiration=7200000