spring.application.name=proye01
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
media.location=mediafiles



# Desactivar estrategia de nombres de Spring que convierte a snake_case
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl


spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/BD100
spring.datasource.username=postgres
spring.datasource.password=5432

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# En application.properties
spring.servlet.multipart.enabled=true


spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
jwt.secret.key=sandoval

jwt.time.expiration=7200000

server.port = 8080
